### ISSUE TITLE
discotc ban you 

### ISSUE THREAD

**Issue by nearlySplat** [X1nto/OpenCord#1]
discorc will ban you because th8rx patry client = selfbot and they ban se,fbtofeajsrvf

**Comment by sudo-nautilus** [comment]
Lmao

**Comment by X1nto** [comment]
Agree

**Comment by sudo-nautilus** [comment]
:trollface:

**Comment by nearlySplat** [comment]
looking back on this, I was either high or asleep.

**Comment by sudo-nautilus** [comment]
https://user-images.githubusercontent.com/78522210/131769798-3f788c18-a57a-43c8-b79c-6ab13937bd68.mp4

We don't care

**Comment by DodoGames7** [comment]
Lmao

**Comment by sudo-nautilus** [comment]
Kek

**Comment by taskylizard** [comment]
didn't ask, didn't care.

**Comment by nearlySplat** [comment]
so you care now?

**Comment by lessgoo00** [comment]
> looking back on this, I was either high or asleep.

Hopefully the latter
