### ISSUE TITLE
Crash during login

### ISSUE THREAD

**Issue by alsoGAMER** [X1nto/OpenCord#12]
Stack trace: https://paste.crdroid.net/Gma8K3

**Comment by X1nto** [comment]
Thanks for the stacktrace! I believe this happens on the Fosscord version?

**Comment by alsoGAMER** [comment]
On the discord one, but i can try the fosscord variant if needed.

**Comment by X1nto** [comment]
No need to test the Fosscord variant. I'll take a look.

**Comment by alsoGAMER** [comment]
Oh wait, isn't this also caused by the account having 2fa enabled?
As i can see [here](https://github.com/X1nto/OpenCord/projects/1#card-68510741) the support isn't here yet.

**Comment by X1nto** [comment]
Oh, maybe. I have yet to add 2FA support but haven't had much time to do that. I also recommend not using your main account too if that's what you're doing, just to be safe from getting your account banned in the alpha stage of OpenCord.

**Comment by X1nto** [comment]
> Oh, maybe. I have yet to add 2FA support but haven't had much time to do that. I also recommend not using your main account too if that's what you're doing, just to be safe from getting your account banned in the pre-alpha stage of OpenCord.

**Comment by alsoGAMER** [comment]
> Oh, maybe. I have yet to add 2FA support but haven't had much time to do that. 

As i suspected, I'll try logging into an account without 2fa right now.

> I also recommend not using your main account too if that's what you're doing, just to be safe from getting your account banned in the pre-alpha stage of OpenCord.

Yeah don't worry, it's a burner account.

**Comment by alsoGAMER** [comment]
[It worked](https://i.imgur.com/8x47fhY.jpg), kinda, so was definitely the 2fa that caused the issue.
Probably the client is trying to get the locale setting for the account, but fails due to missing authentication.

Also I had to press 2 times on login before it was logged in, one to load hcaptcha, then to be logged on.

I suggest refactoring the main screen loaded after logging in, cause this is what is shown: https://i.imgur.com/SRQQJRh.jpg
