### ISSUE TITLE
Login button does nothing

### ISSUE THREAD

**Issue by ThatOneCalculator** [X1nto/OpenCord#14]
Pressing the login button doesnt do anything after filling out my info.

**Comment by itsHanibee** [comment]
same here

**Comment by X1nto** [comment]
If you have 2FA enabled, then that would be the issue. 2FA is still not yet supported

**Comment by itsHanibee** [comment]
nope no 2fa, so good news managed to log in but no channels of guilds or friends show up

**Comment by X1nto** [comment]
> nope no 2fa, so good news managed to log in but no channels of guilds or friends show up

Interesting, it does work for me. I'll need some logs for that

**Comment by itsHanibee** [comment]
> > nope no 2fa, so good news managed to log in but no channels of guilds or friends show up
> 
> Interesting, it does work for me. I'll need some logs for that

no worries, im rooted and i have matlog just tell me what to do and i gotchu

**Comment by X1nto** [comment]
> no worries, im rooted and i have matlog just tell me what to do and i gotchu

Okay, so basically, relaunch opencord, open the drawer and press on guild to fetch the channels, if it doesn't work, go to matlog and export the logs from there, that should be enough.

**Comment by itsHanibee** [comment]
> > no worries, im rooted and i have matlog just tell me what to do and i gotchu
> 
> Okay, so basically, relaunch opencord, open the drawer and press on guild to fetch the channels, if it doesn't work, go to matlog and export the logs from there, that should be enough.

yeah i can do that, also i hate it here can i just dm you in discock? i don't mind being your test guinea pig

**Comment by X1nto** [comment]
> > > no worries, im rooted and i have matlog just tell me what to do and i gotchu
> > 
> > 
> > Okay, so basically, relaunch opencord, open the drawer and press on guild to fetch the channels, if it doesn't work, go to matlog and export the logs from there, that should be enough.
> 
> yeah i can do that, also i hate it here can i just dm you in discock? i don't mind being your test guinea pig

Sure, it'd be much better that way

**Comment by ThatOneCalculator** [comment]
> If you have 2FA enabled, then that would be the issue. 2FA is still not yet supported

Yep, that was my issue.
