### ISSUE TITLE
Unable to Login in.

### ISSUE THREAD

**Issue by IamNickerson** [X1nto/OpenCord#17]
Hi I am trying to log in with my alt account nothing seems to happen when I log in it is stuck in login page and when try pressing the log button nothing seems to happen

**Comment by IamNickerson** [comment]
Is because of the Discord 2fa thingy which causes nothing to happen?

**Comment by X1nto** [comment]
Correct. Closing because it's a duplicate of #15

**Comment by IamNickerson** [comment]
Ok so i need to remove 2fa? to log in? @X1nto

**Comment by X1nto** [comment]
Yes

**Comment by X1nto** [comment]
Or use an account without the 2FA

**Comment by IamNickerson** [comment]
> Yes

Okay i am also not able to register?

**Comment by IamNickerson** [comment]
is it currently work in progress?

**Comment by IamNickerson** [comment]
> Or use an account without the 2FA

Alright

**Comment by X1nto** [comment]
> is it currently work in progress?

Yes, read the README

**Comment by IamNickerson** [comment]
Okay

**Comment by IamNickerson** [comment]
it is better to remove the register button as people are totally dumbass and create more issues saying unable to register

**Comment by X1nto** [comment]
Why? It'll be added eventually

**Comment by IamNickerson** [comment]
Okay
