### ISSUE TITLE
screenshots?

### ISSUE THREAD

**Issue by sheeepdev** [X1nto/OpenCord#4]

**Comment by X1nto** [comment]
I should've probably provided screenshots in README. Anyways:

Main Chat                     |  Drawer
:-------------------------:|:-------------------------:
![Screenshot_1632987443](https://user-images.githubusercontent.com/48173186/135409207-6175bb44-488e-464d-b8f0-98d429115ff8.png)  | ![Screenshot_1632987688](https://user-images.githubusercontent.com/48173186/135409243-55ff4b91-8cb5-4bb9-9235-bc78978b7ba9.png)

It's still in very early stage but I think it mimicks discord's UI perfectly

**Comment by sheeepdev** [comment]
Pretty nice! Thanks. You should put the screenshots into the readme.

**Comment by X1nto** [comment]
> Pretty nice! Thanks. You should put the screenshots into the readme.

Yup, I'll do so!
