### ISSUE TITLE
Support to change api endpoints

### ISSUE THREAD

**Issue by Flam3rboy** [X1nto/OpenCord#6]
Because its against TOS to use this discord client, users might want to change the endpoints to their own selfhosted [fosscord](https://fosscord.com/) server.

**Comment by X1nto** [comment]
A separate version for Fosscord is now supported officially via the [Android Product Flavors](https://developer.android.com/studio/build/build-variants#product-flavors). Check [README](https://github.com/X1nto/OpenCord#where-download) for more info.

**Comment by Flam3rboy** [comment]
Amazing 🎉
