### ISSUE TITLE
app crashes on login

### ISSUE THREAD

**Issue by Laar3** [X1nto/OpenCord#7]
Hi, I've installed the latest apk however once I press the login button after entering my email and password. I'm not sure how to get debug info on android so if there is any info you need you might need to point me towards how to get it.

I'm running lineageos 18 (android 11).

**Comment by X1nto** [comment]
Which version of the app are you using, Fosscord or Normal?

**Comment by Laar3** [comment]
The issue happens on both versions of the app.

**Comment by X1nto** [comment]
In that case, I need you to collect logs.

1. Enable USB debugging on your device and connect it to your PC
2. Download the [Android Platform Tools](https://developer.android.com/studio/releases/platform-tools) and unzip it somewhere, then right-click and open CMD/Window Terminal/Powershell from there.
3. type `adb.exe logcat -c`
4. [Reproduce the crash on device]
5. type `adb.exe logcat > logcat.txt`
6. Terminate the terminal/cmd/powershell oparation
7. A logcat.txt file should appear in the same folder where platform tools was unzipped, send that logcat.txt here.

**Comment by Laar3** [comment]
I'll have to do it tomorrow cause its getting a bit late. I assume the steps will be the same on Linux (other than installing adb)

**Comment by X1nto** [comment]
> I'll have to do it tomorrow cause its getting a bit late. I assume the steps will be the same on Linux (other than installing adb)

On Linux, you can use Pacman or yay (for Arch) and apt (for Debian) to get the `platform-tools` package instead of using the website. Otherwise yeah it's pretty much the same (except you don't have to append `.exe` at the end of `adb`, obviously)

**Comment by X1nto** [comment]
> I'll have to do it tomorrow cause its getting a bit late. I assume the steps will be the same on Linux (other than installing adb)

Hmm, it fails to connect to the gateway with "Connection Refused", but it works fine on my phone. Do you have a firewall set-up by any chance? You might be blocking connection to the Discord servers

**Comment by Laar3** [comment]
I do have a firewall set up however I did allow the app through it (and even tried with the firewall fully disabled)

**Comment by X1nto** [comment]
I'll take a look when I finish implementing the member fetch

**Comment by TheArcaneBrony** [comment]
just saying, the .exe isnt needed on windows either.

**Comment by X1nto** [comment]
Tried many different times, couldn't reproduce the issue at all. I'm guessing it really is your internet. Could you try with different DNS maybe? Either google's or firebase's DNS should work fine

**Comment by Laar3** [comment]
ive actually gotten rid of my android phone now lol (moved to a pinephone), it probably was just the internet or something though.

**Comment by CaptiveNeko03** [comment]
I also have the same problem, I have neither a firewall nor a modified ROM, I have the mobile as I bought it, but the login button does not work

**Comment by ItzOnlyAnimal** [comment]
![no logs?](https://user-images.githubusercontent.com/24845294/172959102-bcfa1464-89bd-42a4-82b8-521f1bfbb588.png)
If anyone has the same issue, please create a new issue **and include a logcat** instead of adding to this one, ty
