### ISSUE TITLE
Support Kit-Kat (4.4.4, API level 19)

### ISSUE THREAD

**Issue by KOLANICH** [X1nto/OpenCord#9]

**Comment by Juby210** [comment]
Why do you want support for an ancient android version, get a custom rom instead of using 8 years old android version.

**Comment by X1nto** [comment]
Impossible.

**Comment by KOLANICH** [comment]
>get a custom rom instead of using 8 years old android version.

Please don't advice anyone on this resource that. Of course I have taken a custom rom. It's just the latest custom rom that works with the blobs. Upgrading further will make the device completely unusable. No wifi, no GPU, only llvmpipe, no camera, no sensors, no GPS. Also Google has intentionally fucked up the build system so much, so it is infeasible to use it. A sane build system should fetch as much binary packages as it can and combine a rom of them and the packages it had to build should be cached and reused. But Google is fond of insane ones. They can afford it, it may be a slightly costly for them, but the benefit of keeping amateurs away outweights the costs.
