### ISSUE TITLE
Hcaptcha immediately closing

### ISSUE THREAD

**Issue by ThatOneCalculator** [X1nto/OpenCord#90]
My account has 2FA on it, and as #77 is open, I can't log in.

**Comment by DiamondMiner88** [comment]
- are you running lastest actions apk? 
- is an hcaptcha popup showing?
- are you tapping out of ^^ or 2fa dialog by mistake? (unlikely but you never know)

**Comment by ThatOneCalculator** [comment]
The hcaptcha popup shows for a second then goes away (and no, I'm not tapping out of it)

**Comment by ThatOneCalculator** [comment]
I'd take a screen recording but I don't wanna dox my phone number/password :woozy_face:

**Comment by ThatOneCalculator** [comment]
I downloaded the latest APK and I got it to work, but the behavior is still inconsistent so I'll leave this issue open for now.
